name: Build and deploy to Kuroco front
on:
  push:
    branches:
      - main
  issue_comment:
    types: [created, edited]
  workflow_dispatch:
    branches: [ main ]
jobs:
  # for Pull Request (exclude merged)
  pullreq_build:
    name: Build(pullreq)
    if: (github.repository == 'nimitbhargava/kuroco-static-site' && github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/kuroco stage') && github.event.issue.pull_request != null)
    runs-on: ubuntu-latest
    steps:
      - name: "Get branch name and sha"
        id: get_branch
        run: |
          PR=$(curl -H "Authorization: token 65faef737c2eb1fcd76b6164959d74ab" https://kemuri-static-site.g3.kuroco.app/direct/menu/github/?pr=${{ github.event.issue.pull_request.url }})
          echo "::set-output name=branch::$(echo $PR | jq -r '.ref')"
          echo "::set-output name=sha::$(echo $PR | jq -r '.sha')"
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_branch.outputs.branch }}
      - name: "Remove .git and .github"
        id: remove_git_github
        run: |
          rm -rf .git
          rm -rf .github
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.get_branch.outputs.sha }}-${{ github.run_id }}
          path: dist
          retention-days: 7
      - name: Wait for Artifact download
        run: sleep 15
      - name: Webhook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: "https://kemuri-static-site.g3.kuroco.app/direct/menu/github/"
          webhook_secret: "65faef737c2eb1fcd76b6164959d74ab"
          data: '{"domain":"kemuri-static-site.g3.kuroco-front.app","pr":"${{ github.event.issue.pull_request.url }}",  "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ steps.get_branch.outputs.sha }}"}'
          
  #for Push
  pushed_build:
    name: Build(pushed)
    if: (github.repository == 'nimitbhargava/kuroco-static-site' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: "Remove .git and .github"
        id: remove_git_github
        run: |
          rm -rf .git
          rm -rf .github
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}-${{ github.run_id }}
          path: ${{ github.workspace }}
          retention-days: 7
      - name: Webhook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: "https://kemuri-static-site.g3.kuroco.app/direct/menu/github/"
          webhook_secret: "65faef737c2eb1fcd76b6164959d74ab"
          data: '{"domain":"kemuri-static-site.g3.kuroco-front.app", "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'
